export default [
  {
    id: 1,
    name: "Tiger Nixon",
    position: "System Architect",
    city: "Edinburgh",
    age: "61",
    createdAt: "2011/04/25",
    salary: "$320,800",
  },
  {
    id: 2,
    name: "Garrett Winters",
    position: "Accountant",
    city: "Tokyo",
    age: "63",
    createdAt: "2011/07/25",
    salary: "$170,750",
  },
  {
    id: 3,
    name: "Ashton Cox",
    position: "Junior Technical Author",
    city: "San Francisco",
    age: "66",
    createdAt: "2009/01/12",
    salary: "$86,000",
  },
  {
    id: 4,
    name: "Cedric Kelly",
    position: "Senior Javascript Developer",
    city: "Edinburgh",
    age: "22",
    createdAt: "2012/03/29",
    salary: "$433,060",
  },
  {
    id: 5,
    name: "Airi Satou",
    position: "Accountant",
    city: "Tokyo",
    age: "33",
    createdAt: "2008/11/28",
    salary: "$162,700",
  }
]
