const getters = {
  areas: state => state.areas,
  areaById: state => state.areaById,
  cabangById: state => state.cabangById,
  axis: state => state.axis,
  axi: state => state.axi,
  included: state => state.included,
  lokasi: state => state.lokasi,
  lokasiIncluded: state => state.lokasiIncluded,
  banks: state => state.banks,
  cabangs: state => state.cabangs,
  cabang: state => state.cabang,
  provinsis: state => state.provinsis,
  kotas: state => state.kotas,
  kecamatans: state => state.kecamatans,
  desas: state => state.desas,
  point: state => state.point,
  count_pendaftaran_axi: state => state.count_pendaftaran_axi,
  jenis_axi: state => state.jenis_axi,
  jenis_kelamin: state => state.jenis_kelamin,
  agama: state => state.agama,
  statusPernikahan: state => state.statusPernikahan,
  legalForm: state => state.legalForm,
  resBCA: state => state.resBCA,
  resDanamon: state => state.resDanamon,
  desaId: state => state.desaId,
  kecamatanbyId: state => state.kecamatanbyId,
  kotabyId: state => state.kotabyId,
  provinsibyId: state => state.provinsibyId,
  resUpdate: state => state.resUpdate,
  crhName: state => state.crhName,
  crhEmail: state => state.crhEmail,
  approveList: state => state.approveList,
  verifikasiDataList: state => state.verifikasiDataList,
  jenisKaryawan: state => state.jenisKaryawan,
};

export default getters;
